services:

#  shardingsphere-proxy:
#    image: apache/shardingsphere-proxy:latest
#    container_name: shardingsphere-proxy
#    ports:
#      - "3308:3308"
#    environment:
#      JVM_OPTS: -Djava.awt.headless=true
#      PORT: 3308
#    volumes:
#      - ./shardingsphere-proxy/conf:/opt/shardingsphere-proxy/conf
# #      Для монтирования файла (не директории)
#      - type: bind
#        source: ./target/transaction-api-1.0.0.jar
#        target: /opt/shardingsphere-proxy/ext-lib/transaction-api-1.0.0.jar
#        read_only: true
#    depends_on:
#      - db0
#      - db1
#      - db2
#      - db3
#    networks:
#      - app-network


  db0:
    image: postgres:latest
    container_name: db0
    ports:
      - 5416:5432
    environment:
      POSTGRES_DB: ds0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--max_prepared_transactions=10"
    command:
          - "postgres"
          - "-c"
          - "max_prepared_transactions=10"
    volumes:
      - db0_data:/var/lib/postgresql/data
    networks:
      - app-network

  db1:
    image: postgres:latest
    container_name: db1
    ports:
      - 5417:5432
    environment:
      POSTGRES_DB: ds1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--max_prepared_transactions=10"
    command:
        - "postgres"
        - "-c"
        - "max_prepared_transactions=10"
    volumes:
      - db1_data:/var/lib/postgresql/data
    networks:
      - app-network

  db2:
    image: postgres:latest
    container_name: db2
    ports:
      - 5418:5432
    environment:
      POSTGRES_DB: ds2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--max_prepared_transactions=10"
    command:
        - "postgres"
        - "-c"
        - "max_prepared_transactions=10"
    volumes:
      - db2_data:/var/lib/postgresql/data
    networks:
      - app-network

  db3:
    image: postgres:latest
    container_name: db3
    ports:
      - 5419:5432
    environment:
      POSTGRES_DB: ds3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--max_prepared_transactions=10"
    command:
        - "postgres"
        - "-c"
        - "max_prepared_transactions=10"
    volumes:
      - db3_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db0_data:
  db1_data:
  db2_data:
  db3_data:

networks:
  app-network:
    name: app-network
    driver: bridge