server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml?allowLoadLocalInfile=true
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform
      hibernate.transaction.coordinator_class: jta
      hibernate.format_sql: true

  flyway:
    enabled: false

#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


flyway:
  dataSources:
    - url: jdbc:postgresql://localhost:5432/ds0
      username: postgres
      password: postgres
    - url: jdbc:postgresql://localhost:5432/ds1
      username: postgres
      password: postgres
    - url: jdbc:postgresql://localhost:5432/ds2
      username: postgres
      password: postgres
    - url: jdbc:postgresql://localhost:5432/ds3
      username: postgres
      password: postgres

logging:
  level:
    org.apache.shardingsphere.sql: TRACE
    org.apache.shardingsphere: TRACE
    com.arjuna: DEBUG
    com.ustsinau: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.web.servlet.filter: DEBUG