server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform
      hibernate.transaction.coordinator_class: jta
      hibernate.format_sql: true


  flyway:
    enabled: false


flyway:
  dataSources:
    - url: jdbc:postgresql://db0:5416/ds0
      username: postgres
      password: postgres
    - url: jdbc:postgresql://db1:5417/ds1
      username: postgres
      password: postgres
    - url: jdbc:postgresql://db2:5418/ds2
      username: postgres
      password: postgres
    - url: jdbc:postgresql://db3:5419/ds3
      username: postgres
      password: postgres

logging:
  level:
    org.apache.shardingsphere.sql: TRACE
    org.apache.shardingsphere: TRACE
    com.arjuna.ats: DEBUG
    org.apache.shardingsphere.transaction: DEBUG
    com.ustsinau: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.web.servlet.filter: DEBUG