server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3308/sharding_db
    username: root  # Используйте пользователя из authority раздела
    password: root
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform
      hibernate.transaction.coordinator_class: jta
      hibernate.format_sql: true

#      hibernate.connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT


  flyway:
    enabled: false

flyway:
  dataSources:
    - url: jdbc:postgresql://db0:5416/ds0
      username: postgres
      password: postgres
    - url: jdbc:postgresql://db1:5417/ds1
      username: postgres
      password: postgres
    - url: jdbc:postgresql://db2:5418/ds2
      username: postgres
      password: postgres
    - url: jdbc:postgresql://db3:5419/ds3
      username: postgres
      password: postgres

logging:
  level:
    org.apache.shardingsphere.sql: TRACE
    org.apache.shardingsphere: TRACE
    com.arjuna.ats: DEBUG
    org.apache.shardingsphere.transaction: DEBUG
    com.ustsinau: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG