databaseName: sharding_db

dataSources:
  ds0:
    url: jdbc:postgresql://db0:5432/ds0
    username: postgres
    password: postgres
  ds1:
    url: jdbc:postgresql://db1:5432/ds1
    username: postgres
    password: postgres
  ds2:
    url: jdbc:postgresql://db2:5432/ds2
    username: postgres
    password: postgres
  ds3:
    url: jdbc:postgresql://db3:5432/ds3
    username: postgres
    password: postgres

rules:

  - !BROADCAST
    tables: # Broadcast tables
      - wallet_types

  - !SHARDING
    tables:

      wallets:
        actualDataNodes: ds${0..3}.wallets
        databaseStrategy:
          standard:
            shardingColumn: user_uid
            shardingAlgorithmName: wallet-hash-mod

      transactions:
        actualDataNodes: ds${0..3}.transactions
        databaseStrategy:
          standard:
            shardingColumn: user_uid
            shardingAlgorithmName: wallet-hash-mod

      payment_requests:
        actualDataNodes: ds${0..3}.payment_requests
        databaseStrategy:
          standard:
            shardingColumn: user_uid
            shardingAlgorithmName: wallet-hash-mod

      top_up_requests:
        actualDataNodes: ds${0..3}.top_up_requests
        databaseStrategy:
          hint:
            shardingAlgorithmName: payment-hash-mod

      withdrawal_requests:
        actualDataNodes: ds${0..3}.withdrawal_requests
        databaseStrategy:
          hint:
            shardingAlgorithmName: payment-hash-mod

      transfer_requests:
        actualDataNodes: ds${0..3}.transfer_requests
        databaseStrategy:
          hint:
            shardingAlgorithmName: payment-hash-mod

    #    bindingTables:
    #      - wallets, payment_requests, transactions

    shardingAlgorithms:

      wallet-hash-mod:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: com.ustsinau.transactionapi.shardingAlgorithm.UUIDHashModShardingAlgorithm


      payment-hash-mod:
        type: CLASS_BASED
        props:
          strategy: HINT
          algorithmClassName: com.ustsinau.transactionapi.shardingAlgorithm.MyHintShardingAlgorithm
